mappingbot/webserver/__init__.py
import os
from pathlib import Path
from threading import Thread

from flask import Flask


def create_app(test_config=None, explorer=None):
    webserver_dir = Path(__file__).parent  # Return the package folder
    instance_dir = Path.joinpath(webserver_dir, 'instance')  # Add the instance folder

    # create and configure the app
    app = Flask(__name__, instance_path=instance_dir, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='mappingbot',
    )

    app.config['EXPLORER_OBJECT'] = explorer

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    # Register all blueprints
    # from mappingbot.webserver.routes import register_all_blueprints
    from webserver.routes import register_all_blueprints
    register_all_blueprints(app)

    return app


class WebserverThread(Thread):

    def __init__(self, host=None, port: int = None, debug=None, load_dotenv: bool = False, test_config=None,
                 explorer=None):
        """
        Create a threaded flask webserver.

        :param host: Hostname (default: localhost)
        :param port: Port nr (default: 5000)
        :param debug: Debugging mode (default: False)
        :param load_dotenv: Load from .flaskenv files (default: False)
        :param test_config: Pass a test config (default: None)
        :param explorer: Explorer data tracking object (default: None)
        """
        super().__init__(daemon=True)
        self.app = create_app(test_config=test_config, explorer=explorer)
        self.host = host
        self.port = port
        self.debug = debug
        self.load_dotenv = load_dotenv
        self.explorer = explorer

    def run(self):
        self.app.run(self.host, self.port, self.debug, self.load_dotenv)


if __name__ == '__main__':
    webserver = WebserverThread(host='0.0.0.0', debug=True)
    webserver.run()  # NOTE: Use .start() instead of .run() to make it run as a thread (recommended)

mappingbot/webserver/routes.py
from flask import Blueprint, render_template, current_app, url_for

from PIL import Image
import numpy as np
import sys
from matplotlib import image

# from mappingbot.constants import DATA_FOLDER_PATH, FILENAME_MAPPINGDATA, FILENAME_BLUETOOTHMAP, FILENAME_DATAMAP, \
#     FILENAME_HISTORYMAP, FILENAME_VIRTUALMAP
from constants import DATA_FOLDER_PATH, FILENAME_MAPPINGDATA, FILENAME_BLUETOOTHMAP, FILENAME_DATAMAP, \
    FILENAME_HISTORYMAP, FILENAME_VIRTUALMAP


def register_all_blueprints(app):
    """Registers all blueprints."""
    app.register_blueprint(bp_main)
    app.register_blueprint(bp_data)
    app.register_blueprint(bp_view)
    app.register_blueprint(bp_raw)


def _rescale_linear(array, new_min, new_max):
    """Rescale an arrary linearly.
    Source: https://stackoverflow.com/questions/36000843/scale-numpy-array-to-certain-range"""
    minimum, maximum = np.min(array), np.max(array)
    m = (new_max - new_min) / (maximum - minimum)
    b = new_min - m * minimum
    return m * array + b


bp_main = Blueprint('main', __name__)


@bp_main.route('/')
@bp_main.route('/index')
@bp_main.route('/home')
def index():
    """A simple index page."""
    return render_template('index.html')


@bp_main.route('/hello')
def hello():
    """A simple page that says hello."""
    return 'Hello, World!'


# ----- Visualizing data in greyscale images -----
bp_view = Blueprint('view', __name__, url_prefix='/view')


@bp_view.route('/')
@bp_view.route('/overview')
def overview():
    datamap_file = datamap()
    mappingdata_file = ''  # mappingdata_filename = mappingdata()  # Mappingdata is disabled
    bluetoothmap_file = bluetoothmap()
    historymap_file = historymap()
    virtualmap_file = virtualmap()
    return render_template('view.html', datamap_file=datamap_file, mappingdata_file=mappingdata_file,
                           bluetoothmap_file=bluetoothmap_file, historymap_file=historymap_file,
                           virtualmap_file=virtualmap_file)


@bp_view.route('/datamap')
def datamap(random=None):
    if current_app.config['EXPLORER_OBJECT'] is not None:
        current_app.config['EXPLORER_OBJECT'].save_data_map()
    data = np.loadtxt(DATA_FOLDER_PATH / FILENAME_DATAMAP, delimiter='  ', )
    data = _rescale_linear(data, 0, 255)  # Rescale the array to greyscale pixels (0,255)
    data = 255 - data  # Invert the pixels (high value -> darker)
    data = data.astype(np.uint8)

    image = Image.fromarray(data)
    image = image.convert("L")
    # image = image.resize((400, 400), resample=Image.BOX)
    image.save(DATA_FOLDER_PATH / 'datamap.jpeg')
    image.save(current_app.static_folder + '/datamap.jpeg')
    return url_for('static', filename='datamap.jpeg')


@bp_view.route('/bluetoothmap')
def bluetoothmap(random=None):
    if current_app.config['EXPLORER_OBJECT'] is not None:
        current_app.config['EXPLORER_OBJECT'].save_bluetooth_map()  # TODO: Look if this exists
    data = np.loadtxt(DATA_FOLDER_PATH / FILENAME_BLUETOOTHMAP, delimiter='  ', )
    data = _rescale_linear(data, 0, 255)  # Rescale the array to greyscale pixels (0,255)
    data = 255 - data  # Invert the pixels (high value -> darker)
    data = data.astype(np.uint8)

    image = Image.fromarray(data)
    image = image.convert("L")
    # image = image.resize((400, 400), resample=Image.BOX)
    image.save(DATA_FOLDER_PATH / 'bluetoothmap.jpeg')
    image.save(current_app.static_folder + '/bluetoothmap.jpeg')
    return url_for('static', filename='bluetoothmap.jpeg')


@bp_view.route('/historymap')
def historymap(random=None):
    if current_app.config['EXPLORER_OBJECT'] is not None:
        current_app.config['EXPLORER_OBJECT'].save_history_map()
    data = np.loadtxt(DATA_FOLDER_PATH / FILENAME_HISTORYMAP, delimiter='  ', )
    data = _rescale_linear(data, 0, 255)  # Rescale the array to greyscale pixels (0,255)
    data = 255 - data  # Invert the pixels (high value -> darker)
    data = data.astype(np.uint8)

    image = Image.fromarray(data)
    image = image.convert("L")
    # image = image.resize((400, 400), resample=Image.BOX)
    image.save(DATA_FOLDER_PATH / 'historymap.jpeg')
    image.save(current_app.static_folder + '/historymap.jpeg')
    return url_for('static', filename='historymap.jpeg')


@bp_view.route('/virtualmap')
def virtualmap(random=None):
    if current_app.config['EXPLORER_OBJECT'] is not None:
        current_app.config['EXPLORER_OBJECT'].save_virtual_map()
    data = np.loadtxt(DATA_FOLDER_PATH / FILENAME_VIRTUALMAP, delimiter='   ', )
    data = _rescale_linear(data, 0, 255)  # Rescale the array to greyscale pixels (0,255)
    data = 255 - data  # Invert the pixels (high value -> darker)
    data = data.astype(np.uint8)

    image = Image.fromarray(data)
    image = image.convert("L")
    # image = image.resize((400, 400), resample=Image.BOX)
    image.save(DATA_FOLDER_PATH / 'virtualmap.jpeg')
    image.save(current_app.static_folder + '/virtualmap.jpeg')
    return url_for('static', filename='virtualmap.jpeg')

# ----- Displaying raw data -----
bp_raw = Blueprint('raw', __name__, url_prefix='/raw')


@bp_raw.route('/mappingdata')
def raw_mappingdata():
    with open(DATA_FOLDER_PATH / FILENAME_MAPPINGDATA) as file:
        lines = file.read()
        return lines


@bp_raw.route('/virtualmap')
def raw_virtualmap():
    with open(DATA_FOLDER_PATH / FILENAME_VIRTUALMAP) as file:
        lines = file.read()
        return lines


@bp_raw.route('/datamap')
def raw_datamap():
    with open(DATA_FOLDER_PATH / FILENAME_DATAMAP) as file:
        lines = file.read()
        return lines


@bp_raw.route('/historymap')
def raw_historymap():
    with open(DATA_FOLDER_PATH / FILENAME_HISTORYMAP) as file:
        lines = file.read()
        return lines


@bp_raw.route('/bluetoothmap')
def raw_bluetoothmap():
    with open(DATA_FOLDER_PATH / FILENAME_BLUETOOTHMAP) as file:
        lines = file.read()
        return lines


# ----- Displaying data in table -----
bp_data = Blueprint('data', __name__, url_prefix='/data')
#
#
# @bp_data.route('/mappingdata')
# def mappingdata():
#     data = np.genfromtxt(DATA_FOLDER_PATH / FILENAME_MAPPINGDATA, delimiter=',')
#     result = np.array2string(data, separator=', ')
#     return result
#
#
# @bp_data.route('/datamap')
# def datamap():
#     data = np.loadtxt(DATA_FOLDER_PATH / FILENAME_DATAMAP, delimiter='  ', )
#     with np.printoptions(threshold=sys.maxsize):
#         result = np.array2string(data, separator=', ')
#     return result

mappingbot/webserver/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
        <meta charset="UTF-8">
        <title>{% block title %}BASE{% endblock title %} - MappingBot</title>

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
              integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
              crossorigin="anonymous">
        <script type=text/javascript src="{{ url_for('static', filename='jquery.js') }}"></script>
    {% endblock head %}
</head>
<body>

<!-- Main content block wrapper -->
<div id="wrapper">

    <!-- Content Wrapper -->
    <div id="regular-content-wrapper" class="container-fluid d-flex flex-column">
        <!-- Actual content -->
        <div id="regular-content" class="container-fluid">

            <div class="row justify-content-center">
                <h1>{% block page_title %}BASE{% endblock page_title %} - MappingBot</h1>
            </div>

            {% block regular_content %}
                <!-- Content in the main section goes here -->
                <h1>This is the base template.</h1>
            {% endblock regular_content %}

                <!-- Footer -->
            <div id="footer" class="footer">
                {% block footer %}
                    <footer class="sticky-footer bg-white">
                        <div class="container my-auto">
                            <div class="copyright text-center my-auto">
                                <span>&copy; Copyright 2021 by Sicco Colijn, Dominik Hafner and Jelle Hierck</span>
                            </div>
                        </div>
                    </footer>
                {% endblock footer %}
            </div> <!-- #footer -->
        </div> <!-- /#regular-content -->
    </div> <!-- /#regular-content-wrapper -->

</div> <!-- /#wrapper -->

{% block script %}

    {# Any extra scripts go here. Always use {% super() %} when adding page-specific scripts #}
{% endblock script %}


</body>
</html>

mappingbot/webserver/templates/index.html
{% extends "base.html" %}

{# Title (not displayed) #}
{% block title %}Home{% endblock title %}

{# Page title (displayed) #}
{% block page_title %}Home{% endblock page_title %}

{# Content #}
{% block regular_content %}

    <div class="row justify-content-center">
        <a href="{{ url_for('view.overview') }}" class="btn btn-primary">Go to View</a>
    </div>

{% endblock regular_content %}

{# Scripts #}
{% block script %}

    {{ super() }}

{% endblock script %}

mappingbot/webserver/templates/view.html
{% extends "index.html" %}

{# Title #}
{% block title %}View{% endblock title %}

{# Page title (displayed) #}
{% block page_title %}View{% endblock page_title %}

{# Content #}
{% block regular_content %}

    <div class="card-group">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Control Panel</h5>
                <p class="card-text">Refresh all images. This will load all currently stored data on the MappingBot and output visualize its current data on this web page.</p>
            </div>
            <div class="card-footer">
                <a onclick="refreshAll();" class="btn btn-primary">Refresh all images</a>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Control Panel</h5>
                <p class="card-text">Make the MappingBot run its regular program.</p>
            </div>
            <div class="card-footer">
                <a href="#" class="btn btn-primary disabled">Drive</a>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Control Panel</h5>
                <p class="card-text">Return to the bluetooth source signal</p>
            </div>
            <div class="card-footer">
                <a href="#" class="btn btn-primary disabled" disabled>Go to Bluetooth</a>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Control Panel</h5>
                <p class="card-text">Action placeholder.</p>
            </div>
            <div class="card-footer">
                <a href="#" class="btn btn-primary disabled" disabled>Disabled</a>
            </div>
        </div>
    </div>

    <hr class="mt-2 mb-3"/>

    <!-- View cards with data images -->
    <div class="card-deck">
        <div class="card text-center" style="width: 18rem;">
            <img id="datamap-image" src="{{ datamap_file }}" class="card-img-top" alt="{{ datamap_file }}">
            <div class="card-body">
                <h5 class="card-title">Data map</h5>
            </div>
            <div class="card-footer">
                <a onclick="refreshDatamap();" class="btn btn-primary">Refresh</a>
            </div>
        </div>

        <div class="card text-center" style="width: 18rem;">
            <img id="virtualmap-image" src="{{ virtualmap_file }}" class="card-img-top" alt="{{ virtualmap_file }}">
            <div class="card-body">
                <h5 class="card-title">Virtual map</h5>
            </div>
            <div class="card-footer">
                <a onclick="refreshVirtualmap();" class="btn btn-primary">Refresh</a>
            </div>
        </div>

        <div class="card text-center" style="width: 18rem;">
            <img id="historymap-image" src="{{ historymap_file }}" class="card-img-top" alt="{{ historymap_file }}">
            <div class="card-body">
                <h5 class="card-title">Current path</h5>
            </div>
            <div class="card-footer">
                <a onclick="refreshHistorymap();" class="btn btn-primary">Refresh</a>
            </div>
        </div>

        <div class="card text-center" style="width: 18rem;">
            <img id="bluetoothmap-image" src="{{ bluetoothmap_file }}" class="card-img-top"
                 alt="{{ bluetoothmap_file }}">
            <div class="card-body">
                <h5 class="card-title">Bluetooth signal strength</h5>
            </div>
            <div class="card-footer">
                <a onclick="refreshBluetoothmap();" class="btn btn-primary">Refresh</a>
            </div>
        </div>


        {#        <div class="card text-center" style="width: 18rem;">#}
        {#            <img src="{{ url_for('static', filename=mappingdata_filename) }}" class="card-img-top"#}
        {#                 alt="{{ url_for('static', filename=mappingdata_filename) }}">#}
        {#            <div class="card-body">#}
        {#                <h5 class="card-title">Mappingdata</h5>#}
        {#                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>#}
        {#                <a href="#" class="btn btn-primary">Refresh</a>#}
        {#            </div>#}
        {#        </div>#}
    </div>

{% endblock regular_content %}

{# Scripts #}
{% block script %}

    <script type="text/javascript">

    $(document).ready(function () {  // Start this when the page is loaded
        setInterval(function () {  // Start a time which will refresh the images once every 15 seconds
            console.log("Reloading images")
            refreshAll()
        }, 15000);
    });

    function refreshDatamap() {
        $.ajax({
            url: '/view/datamap',
        }).done(function (response) {
            console.log(response);
            document.getElementById('datamap-image').src = response.concat("?random=" + new Date().getTime());
        }).fail(function (error) {
            console.log(error);
        })
    }

    function refreshHistorymap() {
        $.ajax({
            url: '/view/historymap',
        }).done(function (response) {
            console.log(response);
            document.getElementById('historymap-image').src = response.concat("?random=" + new Date().getTime());
        }).fail(function (error) {
            console.log(error);
        })
    }

    function refreshVirtualmap() {
        $.ajax({
            url: '/view/virtualmap',
        }).done(function (response) {
            console.log(response);
            document.getElementById('virtualmap-image').src = response.concat("?random=" + new Date().getTime());
        }).fail(function (error) {
            console.log(error);
        })
    }


    function refreshBluetoothmap() {
        $.ajax({
            url: '/view/bluetoothmap',
        }).done(function (response) {
            console.log(response);
            document.getElementById('bluetoothmap-image').src = response.concat("?random=" + new Date().getTime());
        }).fail(function (error) {
            console.log(error);
        })
    }

    function refreshAll() {
        refreshDatamap();
        refreshBluetoothmap();
        refreshHistorymap();
        refreshVirtualmap();
    }

    </script>

    {{ super() }}

{% endblock script %}